// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzn1phiVHLpMYLEbsuDTc2bk6uqVkke4',
    appId: '1:395781486794:web:84b06dadf2a6f34d7b1c33',
    messagingSenderId: '395781486794',
    projectId: 'mariya-ecdfe',
    authDomain: 'mariya-ecdfe.firebaseapp.com',
    storageBucket: 'mariya-ecdfe.appspot.com',
    measurementId: 'G-0ZD1GTYLH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNpuk6NE6BCX_8-MvErhxQ48mWVRy_Bk',
    appId: '1:395781486794:android:95651088b8b8f7717b1c33',
    messagingSenderId: '395781486794',
    projectId: 'mariya-ecdfe',
    storageBucket: 'mariya-ecdfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWwBqcyZsrXNXwkMXmesmldsZbnxvPb3s',
    appId: '1:395781486794:ios:728ee821838c38eb7b1c33',
    messagingSenderId: '395781486794',
    projectId: 'mariya-ecdfe',
    storageBucket: 'mariya-ecdfe.appspot.com',
    iosBundleId: 'com.example.mariya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzn1phiVHLpMYLEbsuDTc2bk6uqVkke4',
    appId: '1:395781486794:web:6228b84c02259da67b1c33',
    messagingSenderId: '395781486794',
    projectId: 'mariya-ecdfe',
    authDomain: 'mariya-ecdfe.firebaseapp.com',
    storageBucket: 'mariya-ecdfe.appspot.com',
    measurementId: 'G-817WC9TZBJ',
  );
}
